// web/src/components/marketing/FrontierSection.tsx
import { Section, SectionHeader } from "./Section";
import { Reveal } from "./Reveal";
import { TerminalMockup } from "./TerminalMockup";
import { FRONTIER_COPY } from "./sections";

export function FrontierSection() {
  return (
    <Section id="demo" className="bg-background">
      <div className="grid items-center gap-12 lg:grid-cols-2">
        <SectionHeader heading={FRONTIER_COPY.heading} subhead={FRONTIER_COPY.subhead} />
        <Reveal direction="right" delay={120}>
          <TerminalMockup />
        </Reveal>
      </div>
    </Section>
  );
}

// web-angular/src/app/components/marketing/frontier-section.component.ts
import { Component } from '@angular/core';
import { SectionComponent, SectionHeaderComponent } from './section.component';
import { RevealDirective } from '../../directives/reveal.directive';
import { TerminalMockupComponent } from './terminal-mockup.component';
import { FRONTIER_COPY } from './sections';

@Component({
  standalone: true,

  selector: 'app-frontier-section',
  imports: [SectionComponent, SectionHeaderComponent, RevealDirective, TerminalMockupComponent],
  template: `
    <app-section id="demo" class="bg-background">
      <div class="grid items-center gap-12 lg:grid-cols-2">
        <app-section-header [subhead]="copy.subhead">{{ copy.heading }}</app-section-header>
        <div appReveal direction="right" [delay]="120">
          <app-terminal-mockup />
        </div>
      </div>
    </app-section>
  `,
})
export class FrontierSectionComponent {
  readonly copy = FRONTIER_COPY;
}
