// web-angular/src/app/components/marketing/quote-flicker.component.ts
import { isPlatformBrowser } from '@angular/common';
import { Component, input, signal, inject, effect, PLATFORM_ID } from '@angular/core';

@Component({
  standalone: true,

  selector: 'app-quote-flicker',
  template: `
    <p [class]="'leading-relaxed ' + class()">
      {{ text().slice(0, visibleChars()) }}
      @if (visibleChars() < text().length) {
        <span class="ml-0.5 inline-block h-4 w-2 animate-pulse bg-foreground align-middle"></span>
      }
    </p>
  `,
})
export class QuoteFlickerComponent {
  readonly text = input.required<string>();
  readonly class = input('');

  readonly visibleChars = signal(0);

  private readonly platformId = inject(PLATFORM_ID);

  constructor() {
    effect(() => {
      const fullText = this.text();
      this.visibleChars.set(0);
      if (!isPlatformBrowser(this.platformId)) {
        this.visibleChars.set(fullText.length);
        return;
      }
      if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
        this.visibleChars.set(fullText.length);
        return;
      }
      let i = 0;
      const interval = window.setInterval(() => {
        i += 1;
        this.visibleChars.set(i);
        if (i >= fullText.length) {
          window.clearInterval(interval);
        }
      }, 12);
      return () => window.clearInterval(interval);
    });
  }
}

// web-react/src/components/marketing/QuoteFlicker.tsx
import { useEffect, useState } from "react";
import { cn } from "@/lib/utils";

export function QuoteFlicker({ text, className }: { text: string; className?: string }) {
  const [visibleChars, setVisibleChars] = useState(0);

  useEffect(() => {
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
      setVisibleChars(text.length);
      return;
    }

    let i = 0;
    const interval = window.setInterval(() => {
      i += 1;
      setVisibleChars(i);
      if (i >= text.length) window.clearInterval(interval);
    }, 12);

    return () => window.clearInterval(interval);
  }, [text]);

  return (
    <p className={cn("leading-relaxed", className)}>
      {text.slice(0, visibleChars)}
      {visibleChars < text.length && (
        <span className="ml-0.5 inline-block h-4 w-2 animate-pulse bg-foreground align-middle" />
      )}
    </p>
  );
}
